version: '3.8'
services:
  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: poland_death_stats
    ports:
    - 3306:3306
    networks:
      - backend
  
  express:
    depends_on:
      - db
    build:
      context: ./server
    ports:
      - 3001:3001/tcp
    networks:
      - backend
      - frontend
  
  # react:
  #   depends_on:
  #     - express
  #   build: 
  #     context: ./client
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - frontend
    
networks:
  backend:
    driver: bridge
  frontend: