version: '3.8'
services:
  db:
    volumes: 
      - db_volume:/var/lib/mysql
      - ./db/polanddeathstats.sql:/docker-entrypoint-initdb.d/polanddeathstats.sql
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: polanddeathstats
    ports:
      - 3306:3306
    networks:
      - backend
      
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin_container
    environment:
      PMA_HOST: db
    links:
      - db:db
    ports:
      - 8081:80
    restart: always
    networks:
      - backend
  # express:
  #   depends_on:
  #     - db
  #   build:
  #     context: ./server
  #   ports:
  #     - 3001:3001
  #   networks:
  #     - backend
  #     - frontend
      
  # # web:
  #   image: nginx
  #   volumes:
  #   - ./client/build:/usr/share/nginx/html
  #   ports:
  #   - "3000:80"
    
networks:
  backend:
    driver: bridge
  frontend:

volumes:
  db_volume: