version: "3.4"

x-common-variables: &common-variables
  MYSQL_USER: sampleuser
  MYSQL_PASSWORD: samplepassword
  MYSQL_DATABASE: polanddeathstats
  REACT_APP_SERVER_PORT: 3001

services:
  mysql-db:
    image: mysql:5.7
#    image: mysql:8.0.29
    container_name: mysql_container
    environment:
      <<: *common-variables
      # MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: password
#      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - ./db/polanddeathstats_full.sql:/docker-entrypoint-initdb.d/polanddeathstats.sql
      - mysql-data:/var/lib/mysql
    networks:
      - backend
  phpmyadmin:
    depends_on:
      - mysql-db
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin_container
    environment:
      PMA_HOST: mysql-db
    links:
      - mysql-db:mysql-db
    ports:
      - 8081:80
    restart: always
    networks:
      - backend
  server:
    restart: always
    build: ./server
    container_name: node_server_container
    depends_on:
      - mysql-db
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql-db
    ports:
      - 3001:3001
    volumes:
      - ./server:/app
    links:
      - mysql-db
    command: npm start
    networks:
      - backend
      - frontend
  client:
    build: ./client
    container_name: client_container
    depends_on:
      - server
    environment:
      <<: *common-variables
      NODE_PATH: src
    ports:
      - 3000:3000
    volumes:
    - ./client/build:/usr/share/nginx/html
    
volumes:
  mysql-data:
  
networks:
  backend:
    driver: bridge
  frontend: