version: "3.4"

x-common-variables: &common-variables
  MYSQL_DATABASE: polanddeathstats
  REACT_APP_SERVER_PORT: 3001

services:
  mysql-db:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - ./db/polanddeathstats_full.sql:/docker-entrypoint-initdb.d/polanddeathstats.sql
      - mysql-data:/var/lib/mysql
    networks:
      - backend
  phpmyadmin:
    depends_on:
      - mysql-db
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin_container
    environment:
      PMA_HOST: mysql-db
    links:
      - mysql-db:mysql-db
    ports:
      - 8081:80
    restart: always
    networks:
      - backend
  server:
    build: ./server
    container_name: node_server_container
    restart: always
    depends_on:
      - mysql-db
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql-db
    ports:
      - 3001:3001
    volumes:
      - ./server:/app
    links:
      - mysql-db
    command: npm start
    networks:
      - backend
      - frontend
  client:
    container_name: client_container
    image: nginx
    volumes:
    - ./client/build:/usr/share/nginx/html
    - ./client/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "3000:80"
    
volumes:
  mysql-data:
  
networks:
  backend:
    driver: bridge
  frontend: