const years = [
  '1999',
  '2000',
  '2001',
  '2002',
  '2003',
  '2004',
  '2005',
  '2006',
  '2007',
  '2008',
  '2009',
  '2010',
  '2011',
  '2012',
  '2013',
  '2014',
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
  '2020'
];

const regionNames = [
  'POLSKA',
  'DOLNOŚLĄSKIE',
  'LUBELSKIE',
  'KUJAWSKO-POMORSKIE',
  'LUBUSKIE',
  'ŁÓDZKIE',
  'PODKARPACKIE',
  'PODLASKIE',
  'MAŁOPOLSKIE',
  'MAZOWIECKIE',
  'POMORSKIE',
  'ŚLĄSKIE',
  'OPOLSKIE',
  'ŚWIĘTOKRZYSKIE',
  'WARMIŃSKO-MAZURSKIE',
  'WIELKOPOLSKIE',
  'ZACHODNIOPOMORSKIE'
];

const deathCauseNames = [
  'razem',
  'niektóre choroby zakaźne i pasożytnicze ogółem',
  'niektóre choroby zakaźne i pasożytnicze - AIDS',
  'nowotwory złośliwe ogółem',
  'nowotwory ogółem',
  'nowotwór złośliwy żołądka, okrężnicy, odbytnicy, złącza jelit i odbytu',
  'nowotwór złośliwy tchawicy, oskrzela i płuca',
  'nowotwór złośliwy kobiecych piersi i szyjki macicy',
  'zaburzenia wydzielania wewnętrznego, stanu odżywiania i przemiany metabolicznej - cukrzyca',
  'zaburzenia psychiczne i zaburzenia zachowania',
  'choroby krwi i narządów krwiotwórczych oraz niektóre choroby przebiegające  z udziałem mechanizmów autoimmunologicznych',
  'zaburzenia wydzielania wewnętrznego, stanu odżywiania i przemiany metabolicznej ogółem',
  'choroby układu nerwowego i narządów zmysłów',
  'choroby układu krążenia ogółem',
  'choroby układu krążenia - choroba nadciśnieniowa',
  'choroby układu krążenia - choroba niedokrwienna serca',
  'choroby układu krążenia - choroby naczyń mózgowych',
  'choroby układu krążenia - miażdżyca',
  'choroby układu oddechowego ogółem',
  'choroby układu oddechowego - zapalenia płuc, zapalenia oskrzeli, rozedma i astma',
  'choroby układu trawiennego ogółem',
  'choroby układu trawiennego - choroba przewlekła wątroby i marskość wątroby',
  'choroby skóry i tkanki podskórnej',
  'choroby układu kostnostawowego, mięśniowego i tkanki łącznej',
  'choroby układu moczowo-płciowego',
  'ciąża, poród i połóg',
  'niektóre stany rozpoczynające się w okresie okołoporodowym',
  'wady rozwojowe wrodzone, zniekształcenia i aberracje chromosomowe',
  'objawy, cechy chorobowe oraz nieprawidłowe wyniki badań klinicznych, laboratoryjnych gdzie indziej niesklasyfikowane',
  'zewnętrzne przyczyny zachorowania i zgonu - ogółem',
  'zewnętrzne przyczyny zachorowania i zgonu - wypadki i nieszczęśliwe następstwa wypadków ogółem',
  'zewnętrzne przyczyny zachorowania i zgonu - wypadki i nieszczęśliwe następstwa wypadków - wypadki komunikacyjne ogółem',
  'zewnętrzne przyczyny zachorowania i zgonu - wypadki i nieszczęśliwe następstwa wypadków - wypadki komunikacyjne - wypadki w ruchu pojazdów silnikowych',
  'zewnętrzne przyczyny zachorowania i zgonu - wypadki i nieszczęśliwe następstwa wypadków - inne zewnętrzne przyczyny urazu wypadkowego',
  'zewnętrzne przyczyny zachorowania i zgonu - samobójstwo',
  'zewnętrzne przyczyny zachorowania i zgonu - zabójstwo',
  'brak przyczyny zgonu (opisu) w Karcie Statystycznej do Karty Zgonu',
  'COVID-19'
];


export { years, regionNames, deathCauseNames };